export const Constants ={
    TEMPLATES:{
        START:"START",
        QUESTION: "QUESTION",
        SHOW_TOPIC:"SHOW_TOPIC",
        ANSWER:"ANSWER"
    },
    PLATFORM:{
        ALEXA:"alexa"
    },
    TAGS:{
        AUDIO:"AUDIO"
    },
    STRINGS:{
        QUESTION_TAG:"QUESTION_TAG",
        DEVICE_TIMEZONE:"DEVICE_CONFIG.DEVICE_TIMEZONE",
        USER_ID: "USER_ID",
        LAST_QUESTION_TYPE: "LAST_QUESTION_TYPE",
        LAST_QUESTION:"LAST_QUESTION",
        PLATFORM:"PLATFORM",
        LAST_SPEECH:"LAST_SPEECH",
        APPNAME:"APPNAME",
        IS_MONETIZATION_ENABLED:"IS_MONETIZATION_ENABLED",
        SESSION_DATA:"sessionContext.sessionData",
        USER_DATA:"sessionContext.userData",
        SUBSCRIPTION_DETAILS:"SUBSCRIPTION_DETAILS",
        LOCALE: "LOCALE",
        LOCALE_CONTENT: "LOCALE_CONTENT",
        IS_DISPLAY_ENABLED: "IS_DISPLAY_ENABLED",
        SESSION_COUNT: "SESSION_COUNT",
        USER_STATE: "USER_STATE",
        STAGE:"STAGE",
        DEVICE_SIZE:"DEVICE_CONFIG.DEVICE_SIZE",
        ROUND_DATA:"ROUND_DATA",
        NO_OF_QUE_FETCHED: "ROUND_DATA.noOfQuestionsFetched",
        TODAYS_QUESTION:"TODAYS_QUESTION",
        BONUS_QUESTION:"BONUS_QUESTION"
    },
    ACTIONS:{
        LAUNCH:"LAUNCH",
        INVALID_ACTION_APPOLOGY:"INVALID_ACTION_APPOLOGY",
        INVALID_CLOSE:"INVALID_CLOSE"
    },
    SEND_EVENT:{
        ASK_QUESTION:"ASK_QUESTION",
        SHOW_TOPIC:"SHOW_TOPIC"
    },
    URLS:{
        TEMPLATE:"TEMPLATE",
        TOPIC_LOGO:"TOPIC_LOGO",
        START_LOGO:"START_LOGO",
        DEFAULT_BG:"DEFAULT_BG",
        WELCOME_AUDIO:"WELCOME_AUDIO"
    },
    FILE_NAMES: {
        LANG_RESOURCE: "languageResources.json",
        APP_CONFIG: "appConfig.json",
        CONSTANTS: "Constants.json"
    }
}